version: "3.4"

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8090:8090"

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
